[project]
name = "embeddings-sdk"
version = "0.1.0"
description = "Python SDK for Embedding Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["grpcio>=1.71.0", "grpcio-tools>=1.71.0"]
